set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN H4} [get_ports clk]

set_property PACKAGE_PIN R4 [get_ports clk_to_change_data_in]
set_property IOSTANDARD LVCMOS18 [get_ports clk_to_change_data_in]
set_property IOSTANDARD LVCMOS18 [get_ports w_en]
set_property IOSTANDARD LVCMOS18 [get_ports {addr[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {addr[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {addr[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {addr[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {addr[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {addr[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_sel[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_sel[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[0]}]
set_property PACKAGE_PIN T3 [get_ports {addr[5]}]
set_property PACKAGE_PIN U3 [get_ports {addr[4]}]
set_property PACKAGE_PIN T4 [get_ports {addr[3]}]
set_property PACKAGE_PIN V3 [get_ports {addr[2]}]
set_property PACKAGE_PIN V4 [get_ports {addr[1]}]
set_property PACKAGE_PIN Y4 [get_ports w_en]
set_property PACKAGE_PIN W4 [get_ports {addr[0]}]
set_property PACKAGE_PIN Y6 [get_ports {data_sel[1]}]
set_property PACKAGE_PIN W7 [get_ports {data_sel[0]}]

set_property PACKAGE_PIN H19 [get_ports {seg[7]}]
set_property PACKAGE_PIN G20 [get_ports {seg[6]}]
set_property PACKAGE_PIN J22 [get_ports {seg[5]}]
set_property PACKAGE_PIN K22 [get_ports {seg[4]}]
set_property PACKAGE_PIN K21 [get_ports {seg[3]}]
set_property PACKAGE_PIN H20 [get_ports {seg[2]}]
set_property PACKAGE_PIN H22 [get_ports {seg[1]}]
set_property PACKAGE_PIN J21 [get_ports {seg[0]}]
set_property PACKAGE_PIN L21 [get_ports {sel[3]}]
set_property PACKAGE_PIN M22 [get_ports {sel[2]}]
set_property PACKAGE_PIN M21 [get_ports {sel[1]}]
set_property PACKAGE_PIN N22 [get_ports {sel[0]}]

set_property PULLDOWN true [get_ports w_en]
set_property PULLDOWN true [get_ports {addr[5]}]
set_property PULLDOWN true [get_ports {addr[4]}]
set_property PULLDOWN true [get_ports {addr[3]}]
set_property PULLDOWN true [get_ports {addr[2]}]
set_property PULLDOWN true [get_ports {addr[1]}]
set_property PULLDOWN true [get_ports {addr[0]}]
set_property PULLDOWN true [get_ports {data_sel[1]}]
set_property PULLDOWN true [get_ports {data_sel[0]}]
